import { createAppTemplate } from "./template.js";

function getById(root, id) {
  return root.querySelector(`#${id}`);
}

export function mountApp(root) {
  root.innerHTML = createAppTemplate();

  return {
    root,
    app: root.querySelector(".ff-app"),
    loader: getById(root, "authLoader"),
    landingPage: getById(root, "landingPage"),
    mainApp: getById(root, "mainApp"),
    toastStack: getById(root, "toastStack"),
    topAuthButton: getById(root, "topAuthButton"),
    landingSignInButton: getById(root, "landingSignInButton"),
    landingAccountToolbar: getById(root, "landingAccountToolbar"),
    landingStreakBadge: getById(root, "landingStreakBadge"),
    landingStreakValue: getById(root, "landingStreakValue"),
    landingThemeToggleButton: getById(root, "landingThemeToggleButton"),
    landingThemeButtonLabel: getById(root, "landingThemeButtonLabel"),
    landingProfileButton: getById(root, "landingProfileButton"),
    landingUserAvatar: getById(root, "landingUserAvatar"),
    landingUserName: getById(root, "landingUserName"),
    landingHeroTitle: getById(root, "landingHeroTitle"),
    navAppButton: getById(root, "navAppButton"),
    landingLoggedOut: getById(root, "landingLoggedOut"),
    landingLoggedIn: getById(root, "landingLoggedIn"),
    landingMemberMessage: getById(root, "landingMemberMessage"),
    publicMinutesMetric: getById(root, "publicMinutesMetric"),
    publicSessionMetric: getById(root, "publicSessionMetric"),
    publicUserMetric: getById(root, "publicUserMetric"),
    landingGoalProgress: getById(root, "landingGoalProgress"),
    landingGoalFill: getById(root, "landingGoalFill"),
    landingTodayMinutes: getById(root, "landingTodayMinutes"),
    landingSessionCount: getById(root, "landingSessionCount"),
    landingLevelName: getById(root, "landingLevelName"),
    landingTotalScore: getById(root, "landingTotalScore"),
    landingLeaderboard: getById(root, "landingLeaderboard"),
    landingSignedMinutesMetric: getById(root, "landingSignedMinutesMetric"),
    landingSignedSessionMetric: getById(root, "landingSignedSessionMetric"),
    landingSignedLiveMetric: getById(root, "landingSignedLiveMetric"),
    landingPreviewProgress: getById(root, "landingPreviewProgress"),
    landingPreviewTimer: getById(root, "landingPreviewTimer"),
    landingPreviewStartButton: getById(root, "landingPreviewStartButton"),
    landingPreviewStopButton: getById(root, "landingPreviewStopButton"),
    landingPreviewResetButton: getById(root, "landingPreviewResetButton"),
    landingPreviewStatusDot: getById(root, "landingPreviewStatusDot"),
    landingPreviewStatusLabel: getById(root, "landingPreviewStatusLabel"),
    landingPreviewDistractions: getById(root, "landingPreviewDistractions"),
    landingPreviewSessionCount: getById(root, "landingPreviewSessionCount"),
    landingPreviewFocusedMinutes: getById(root, "landingPreviewFocusedMinutes"),
    landingPresenceList: getById(root, "landingPresenceList"),
    landingHostToggle: getById(root, "landingHostToggle"),
    landingHostPanel: getById(root, "landingHostPanel"),
    landingHostList: getById(root, "landingHostList"),
    workspaceBanner: getById(root, "workspaceBanner"),
    quoteBar: getById(root, "quoteBar"),
    workspaceStreakBadge: getById(root, "workspaceStreakBadge"),
    workspaceStreakValue: getById(root, "workspaceStreakValue"),
    roomModeCountBadge: getById(root, "roomModeCountBadge"),
    ownerDashButton: getById(root, "ownerDashButton"),
    themeToggleButton: getById(root, "themeToggleButton"),
    themeToggleThumb: getById(root, "themeToggleThumb"),
    themeButtonLabel: getById(root, "themeButtonLabel"),
    profileButton: getById(root, "profileButton"),
    profileAvatar: getById(root, "profileAvatar"),
    profileButtonName: getById(root, "profileButtonName"),
    profilePanel: getById(root, "profilePanel"),
    profilePanelAvatar: getById(root, "profilePanelAvatar"),
    profilePanelName: getById(root, "profilePanelName"),
    profilePanelEmail: getById(root, "profilePanelEmail"),
    profilePanelLevel: getById(root, "profilePanelLevel"),
    profilePanelStreak: getById(root, "profilePanelStreak"),
    profilePanelSessions: getById(root, "profilePanelSessions"),
    profilePanelHours: getById(root, "profilePanelHours"),
    profilePanelScore: getById(root, "profilePanelScore"),
    profileThemeLabel: getById(root, "profileThemeLabel"),
    notificationLabel: getById(root, "notificationLabel"),
    focusGoalInput: getById(root, "focusGoalInput"),
    roomPanel: getById(root, "roomPanel"),
    roomCodeInput: getById(root, "roomCodeInput"),
    roomJoinInput: getById(root, "roomJoinInput"),
    activeRoomLabel: getById(root, "activeRoomLabel"),
    activeRoomCodeLabel: getById(root, "activeRoomCodeLabel"),
    roomPresenceCount: getById(root, "roomPresenceCount"),
    roomOwnerLabel: getById(root, "roomOwnerLabel"),
    roomSyncLabel: getById(root, "roomSyncLabel"),
    roomPresenceList: getById(root, "roomPresenceList"),
    timerRing: getById(root, "timerRing"),
    timerProgress: getById(root, "timerProgress"),
    timerValue: getById(root, "timerValue"),
    timerPercentLabel: getById(root, "timerPercentLabel"),
    timerPhaseLabel: getById(root, "timerPhaseLabel"),
    customDurationPanel: getById(root, "customDurationPanel"),
    customMinutesInput: getById(root, "customMinutesInput"),
    pomodoroButton: getById(root, "pomodoroButton"),
    startButton: getById(root, "startButton"),
    stopButton: getById(root, "stopButton"),
    scoreRuleLabel: getById(root, "scoreRuleLabel"),
    scorePenaltyLabel: getById(root, "scorePenaltyLabel"),
    sessionModeDescription: getById(root, "sessionModeDescription"),
    ambientTrackLabel: getById(root, "ambientTrackLabel"),
    volumeInput: getById(root, "volumeInput"),
    dailyGoalLabel: getById(root, "dailyGoalLabel"),
    dailyGoalFill: getById(root, "dailyGoalFill"),
    sessionSummary: getById(root, "sessionSummary"),
    summaryHeadline: getById(root, "summaryHeadline"),
    saveStateBadge: getById(root, "saveStateBadge"),
    summaryTimeValue: getById(root, "summaryTimeValue"),
    summaryDistractionValue: getById(root, "summaryDistractionValue"),
    summaryScoreValue: getById(root, "summaryScoreValue"),
    summaryFocusValue: getById(root, "summaryFocusValue"),
    sessionFeedback: getById(root, "sessionFeedback"),
    distractionLog: getById(root, "distractionLog"),
    statsStreakValue: getById(root, "statsStreakValue"),
    statsSessionValue: getById(root, "statsSessionValue"),
    statsHoursValue: getById(root, "statsHoursValue"),
    statsLevelValue: getById(root, "statsLevelValue"),
    xpCurrentLabel: getById(root, "xpCurrentLabel"),
    xpNextLabel: getById(root, "xpNextLabel"),
    xpFill: getById(root, "xpFill"),
    badgeCountLabel: getById(root, "badgeCountLabel"),
    badgeList: getById(root, "badgeList"),
    calendarToggleLabel: getById(root, "calendarToggleLabel"),
    calendarMetaLabel: getById(root, "calendarMetaLabel"),
    calendarSection: getById(root, "calendarSection"),
    calendarMonthLabel: getById(root, "calendarMonthLabel"),
    calendarNextButton: getById(root, "calendarNextButton"),
    calendarLongestLabel: getById(root, "calendarLongestLabel"),
    calendarMonthDaysLabel: getById(root, "calendarMonthDaysLabel"),
    calendarGrid: getById(root, "calendarGrid"),
    weekConsistencyLabel: getById(root, "weekConsistencyLabel"),
    weekChart: getById(root, "weekChart"),
    historySection: getById(root, "historySection"),
    historyList: getById(root, "historyList"),
    progressSection: getById(root, "progressSection"),
    leaderboardSection: getById(root, "leaderboardSection"),
    globalLeaderboard: getById(root, "globalLeaderboard"),
    roomLeaderboard: getById(root, "roomLeaderboard"),
    ownerDashboard: getById(root, "ownerDashboard"),
    ownerRoomSelect: getById(root, "ownerRoomSelect"),
    odTotalParticipants: getById(root, "odTotalParticipants"),
    odFocusingCount: getById(root, "odFocusingCount"),
    odDistractedCount: getById(root, "odDistractedCount"),
    odLeftCount: getById(root, "odLeftCount"),
    odParticipants: getById(root, "odParticipants"),
    odEventLog: getById(root, "odEventLog"),
    distractionModal: getById(root, "distractionModal"),
    distractionModalText: getById(root, "distractionModalText"),
    badgeModal: getById(root, "badgeModal"),
    badgeModalTitle: getById(root, "badgeModalTitle"),
    badgeModalText: getById(root, "badgeModalText"),
    sessionModeButtons: [...root.querySelectorAll("[data-session-mode]")],
    modeButtons: [...root.querySelectorAll("[data-mode]")],
    durationButtons: [...root.querySelectorAll("[data-duration]")],
    soundButtons: [...root.querySelectorAll("[data-sound]")],
    boardButtons: [...root.querySelectorAll("[data-board]")]
  };
}


